environment: default
server:
  port: 6969
welcomeMsg: "Hello from the other side(!)"
---
environment: test
server:
  port: 4000
welcomeMsg: "Hello from test"
---
environment: prod
server:
  port: 5000
welcomeMsg: "Hello from prod"